### ISSUE TITLE
mac系统下启动项目报错

### ISSUE THREAD

**Issue by CrazyKidCN** [bbossgroups/bboss#20]
mac下启动项目报错：（在windows系统下正常)

```java
org.frameworkset.security.session.SignSessionIDException: Design sessionid failed:paramenterSessionID=false, signedSessionid=8c169ab2b5c801a0dc9a97838cd73bf750a930440f7ad64470fe2a1cef6283347ec68db32ef1e0981b01b72570227eff
		at org.frameworkset.security.session.impl.WrapperSessionIDGenerator._aesdesign(WrapperSessionIDGenerator.java:108)
		at org.frameworkset.security.session.impl.WrapperSessionIDGenerator.design(WrapperSessionIDGenerator.java:64)
		at org.frameworkset.security.session.impl.SessionHttpServletRequestWrapper.initSessionIDFromCookie(SessionHttpServletRequestWrapper.java:146)
		at org.frameworkset.security.session.impl.SessionHttpServletRequestWrapper.<init>(SessionHttpServletRequestWrapper.java:74)
		at org.frameworkset.security.session.impl.SessionFilter.buildSessionHttpServletRequestWrapper(SessionFilter.java:66)
		at org.frameworkset.security.session.impl.SessionFilter.doFilter(SessionFilter.java:106)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.tcsoft.filter.RequestManageFilter.doFilter(RequestManageFilter.java:83)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
		at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
		at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
		at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
		at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
		at javax.crypto.Cipher.doFinal(Cipher.java:2164)
		at org.frameworkset.security.AESCoder.decrypt(AESCoder.java:91)
		at org.frameworkset.security.session.impl.WrapperSessionIDGenerator._aesdesign(WrapperSessionIDGenerator.java:101)
		... 27 more
```

搜索引擎查找到可能原因
https://blog.csdn.net/pompeii/article/details/20873603

不知能否帮忙解决，感谢

**Comment by CrazyKidCN** [comment]
直接运行 org.frameworkset.security.AESCoder 的 main 会报相同错误
按搜索引擎查找到的方法改写之后运行 main 不再报错，重新打 jar 包并放入项目后却没能解决错误

最后无奈只得将
```
<property name="sessionManager" class="org.frameworkset.security.session.impl.SessionManager"
      <property name="signSessionID" value="true"/>
</property>
```
`true`改`false`后，才不再报错。。。

无奈本人能力有限，只得悄悄在这反映个 issue 希望作者能够解决。。。
